language: julia

sudo: false

os:
  - linux
  - osx
  - windows

julia:
  - 0.6
  - 0.7
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - nightly

matrix:
  allow_failures:
    - julia: nightly
    - os: osx

after_success:
  - julia -e 'cd(Pkg.dir("Ripemd")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
