language: julia

os:
  - linux
  - osx

julia:
  - 0.6
  - nightly

notifications:
  email: false

sudo: false

before_script:
  - julia -e 'Pkg.add("Nettle")'

after_success:
  - julia -e 'cd(Pkg.dir("Ripemd")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
