language: julia

sudo: false

os:
  - linux
  - osx

julia:
  - 0.6
  - nightly

matrix:
  allow_failures:
    - nightly

addons:
  apt:
    packages:
      - libnettle4


before_script:
  - julia -e 'Pkg.add("Nettle"); Pkg.build("Nettle")'

after_success:
  - julia -e 'cd(Pkg.dir("Ripemd")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
